services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: gymsynk
      POSTGRES_USER: gymsynk
      POSTGRES_PASSWORD: gymsynk_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gymsynk"]
      interval: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata_dev:/data

volumes:
  pgdata_dev:
  redisdata_dev: